version: '3.1'

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: Admin
      POSTGRES_PASSWORD: example
      POSTGRES_DB: postgres
    networks:
      - test
  
  python:
    build: ./app/
    depends_on:
      - db
    networks:
      - test
    volumes:
      - ./app:/usr/src/app
      

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      - test

networks:
  test:

