version: '3.1'

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: Admin
      POSTGRES_PASSWORD: example
      POSTGRES_DB: postgres
    networks:
      - test

  # python:
  #     build: ./app/
  #     depends_on:
  #       - db
  #     networks:
  #       - test
  #     volumes:
  #       - ./app:/usr/src/app
  
  python-lab-1:
      build: ./app_lab1/
      depends_on:
        db:
          condition: service_started
        # python:
        #   condition: service_completed_successfully
      networks:
        - test
      volumes:
        - ./app_lab1:/usr/src/app
  
  flyway:
    image: flyway/flyway
    command: -url=jdbc:postgresql://db:5432/postgres -user=Admin -password=example migrate
    volumes:
      - ./sql:/flyway/sql
    depends_on:
        db:
          condition: service_started
        python-lab-1:
          condition: service_completed_successfully
    environment:
      - FLYWAY_BASELINE_ON_MIGRATE=true
    networks:
      - test

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      - test
  

networks:
  test:

